[project]
name = "cellzarr"
version = "0.1.0"
description = " CellZarr is a reproducible workflow for high-content analysis of live-cell timelapse imaging, processing raw ND2 files to quantitative features for scalable biological analysis. "
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pandas",
    "scipy",
    "nd2",
    "scikit-image",
    "matplotlib",
    "tifffile",
    "zarr",
    "ome-zarr <= v0.11.1",
    "dask",
    "natsort",
    "trackpy",
    "edt",
    "magicgui",
    "ipykernel",
    "jupyterlab",
    "ipywidgets",
    "distributed",
    "dask-jobqueue",
    "bokeh",
    "pyarrow",
    "tqdm",

]

[project.optional-dependencies]
colony_seg = [
    "napari-convpaint",
    "napari >=0.6.0",
]


stardist_seg = [
    "stardist",
    "csbdeep",
    "tensorflow",
    "tensorflow_io_gcs_filesystem <= 0.31.0",
    "numpy < 2.0.0"
    ]


cellpose_seg_cpu = [
    "cellpose",
    "numpy",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
cellpose_seg_cuda128 = [
    "cellpose",
    "numpy",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]

trackastra = [
    "trackastra",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "motile"
     ]





[tool.uv]
conflicts = [
  [
    { extra = "cellpose_seg_cpu" },
    { extra = "cellpose_seg_cuda128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cellpose_seg_cpu" },
  { index = "pytorch-cu128", extra = "cellpose_seg_cuda128" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cellpose_seg_cpu" },
  { index = "pytorch-cu128", extra = "cellpose_seg_cuda128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
